-- v2: 住所・階・メモ・捜索開始/終了時刻 (INSARAG) を追加
ALTER TABLE pins ADD COLUMN address  TEXT NOT NULL DEFAULT '';
ALTER TABLE pins ADD COLUMN floor    TEXT NOT NULL DEFAULT '';
ALTER TABLE pins ADD COLUMN note     TEXT NOT NULL DEFAULT '';
ALTER TABLE pins ADD COLUMN start_at INTEGER;
ALTER TABLE pins ADD COLUMN end_at   INTEGER;
